/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookViewsRouteImport } from './routes/book-views'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicQuestionsReportRouteImport } from './routes/api/public/questions-report'
import { Route as ApiPublicRefreshViewsRouteImport } from './routes/api/public/refresh-views'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookViewsRoute = BookViewsRouteImport.update({
  id: '/book-views',
  path: '/book-views',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuestionsReportRoute =
  ApiPublicQuestionsReportRouteImport.update({
    id: '/api/public/questions-report',
    path: '/api/public/questions-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRefreshViewsRoute = ApiPublicRefreshViewsRouteImport.update({
  id: '/api/public/refresh-views',
  path: '/api/public/refresh-views',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-views': typeof BookViewsRoute
  '/promo': typeof PromoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/questions-report': typeof ApiPublicQuestionsReportRoute
  '/api/public/refresh-views': typeof ApiPublicRefreshViewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-views': typeof BookViewsRoute
  '/promo': typeof PromoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/questions-report': typeof ApiPublicQuestionsReportRoute
  '/api/public/refresh-views': typeof ApiPublicRefreshViewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-views': typeof BookViewsRoute
  '/promo': typeof PromoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/questions-report': typeof ApiPublicQuestionsReportRoute
  '/api/public/refresh-views': typeof ApiPublicRefreshViewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book-views'
    | '/promo'
    | '/api/chat'
    | '/api/public/questions-report'
    | '/api/public/refresh-views'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-views'
    | '/promo'
    | '/api/chat'
    | '/api/public/questions-report'
    | '/api/public/refresh-views'
  id:
    | '__root__'
    | '/'
    | '/book-views'
    | '/promo'
    | '/api/chat'
    | '/api/public/questions-report'
    | '/api/public/refresh-views'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookViewsRoute: typeof BookViewsRoute
  PromoRoute: typeof PromoRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicQuestionsReportRoute: typeof ApiPublicQuestionsReportRoute
  ApiPublicRefreshViewsRoute: typeof ApiPublicRefreshViewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-views': {
      id: '/book-views'
      path: '/book-views'
      fullPath: '/book-views'
      preLoaderRoute: typeof BookViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/questions-report': {
      id: '/api/public/questions-report'
      path: '/api/public/questions-report'
      fullPath: '/api/public/questions-report'
      preLoaderRoute: typeof ApiPublicQuestionsReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-views': {
      id: '/api/public/refresh-views'
      path: '/api/public/refresh-views'
      fullPath: '/api/public/refresh-views'
      preLoaderRoute: typeof ApiPublicRefreshViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookViewsRoute: BookViewsRoute,
  PromoRoute: PromoRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicQuestionsReportRoute: ApiPublicQuestionsReportRoute,
  ApiPublicRefreshViewsRoute: ApiPublicRefreshViewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
